@startuml

class KonvaShape {
  (mvc:model)
}
class DrawLayer {
  (mvc:view)
}
class DrawController

circle User

KonvaShape --> DrawLayer: updates
DrawLayer -- User: sees
User -up-> DrawController: uses
DrawController -up-> KonvaShape: manipulates

@enduml
