@startuml

class XMLHttpRequest #lightblue;line:green
class FileReader #lightblue;line:green

class App {
  loadURLs()
  loadFiles()
  loadImageObject()
}
class LoadController
class UrlsLoader
class FilesLoader
class MemoryLoader
interface SpecificDataLoader ##[dashed] {
  canLoadUrl()
  canLoadFile()
}

App ..> LoadController: Uses
LoadController ..> UrlsLoader: Uses
LoadController ..> FilesLoader: Uses
LoadController ..> MemoryLoader: Uses

UrlsLoader .up.> XMLHttpRequest: Uses
FilesLoader .up.> FileReader: Uses

UrlsLoader ..> SpecificDataLoader: Uses
FilesLoader ..> SpecificDataLoader: Uses
MemoryLoader ..> SpecificDataLoader: Uses

@enduml
